"""
SHL Individual Test Solutions Catalog
Scraped from https://www.shl.com/solutions/products/product-catalog/
type=1 = Individual Test Solutions (scope of this project)

Test type codes:
A = Ability / Aptitude
B = Biodata / Situational Judgement  
C = Competencies
K = Knowledge / Skills
P = Personality
S = Simulation
"""

CATALOG = [
    # ── COGNITIVE / ABILITY ───────────────────────────────────────────────
    {
        "name": "Verify Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-numerical-reasoning/",
        "test_type": ["A"],
        "description": "Measures ability to understand and apply numerical concepts. Suitable for professional and managerial roles requiring data interpretation and quantitative reasoning.",
        "job_levels": ["Manager", "Professional", "Graduate"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 17,
        "languages": 30,
    },
    {
        "name": "Verify Verbal Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-reasoning/",
        "test_type": ["A"],
        "description": "Measures ability to evaluate the logic of various kinds of argument. Ideal for roles requiring strong written communication and comprehension.",
        "job_levels": ["Manager", "Professional", "Graduate"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 17,
        "languages": 30,
    },
    {
        "name": "Verify Inductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-inductive-reasoning/",
        "test_type": ["A"],
        "description": "Measures ability to draw inferences and understand relationships between abstract concepts. Good for roles requiring innovation and problem-solving.",
        "job_levels": ["Manager", "Professional", "Graduate"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 24,
        "languages": 30,
    },
    {
        "name": "Verify Deductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-deductive-reasoning/",
        "test_type": ["A"],
        "description": "Measures ability to draw logical conclusions from given information. Suitable for analytical and technically demanding roles.",
        "job_levels": ["Manager", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 15,
    },
    {
        "name": "Verify Mechanical Comprehension",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-mechanical-comprehension/",
        "test_type": ["A"],
        "description": "Measures understanding of mechanical and physical principles. Ideal for engineering, technical, and operational roles.",
        "job_levels": ["Operative", "Technician", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 10,
    },
    {
        "name": "Verify Checking",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-checking/",
        "test_type": ["A"],
        "description": "Measures speed and accuracy in checking data. Suited for clerical, administrative, and data processing roles.",
        "job_levels": ["Entry", "Administrative", "Clerical"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 7,
        "languages": 20,
    },
    {
        "name": "Verify G+",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-g-plus/",
        "test_type": ["A"],
        "description": "Adaptive measure of general cognitive ability combining numerical, verbal and inductive reasoning. Fastest way to get a broad cognitive picture.",
        "job_levels": ["Graduate", "Manager", "Professional"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 36,
        "languages": 30,
    },
    {
        "name": "General Ability",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/general-ability/",
        "test_type": ["A"],
        "description": "Measures general intelligence / g-factor across verbal, numerical and abstract reasoning. Classic broad cognitive assessment.",
        "job_levels": ["Graduate", "Manager", "Professional", "Director"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 36,
        "languages": 20,
    },
    {
        "name": "Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/numerical-reasoning/",
        "test_type": ["A"],
        "description": "Traditional numerical reasoning test measuring ability to understand and work with numerical data. For roles requiring financial and quantitative analysis.",
        "job_levels": ["Graduate", "Manager", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 30,
    },
    {
        "name": "Verbal Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verbal-reasoning/",
        "test_type": ["A"],
        "description": "Traditional verbal reasoning test measuring ability to analyse written information. For roles requiring strong comprehension and communication skills.",
        "job_levels": ["Graduate", "Manager", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 19,
        "languages": 30,
    },
    {
        "name": "Inductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/inductive-reasoning/",
        "test_type": ["A"],
        "description": "Traditional inductive reasoning test measuring ability to identify patterns and relationships. Good for innovation-heavy and technology roles.",
        "job_levels": ["Graduate", "Manager", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 20,
    },
    {
        "name": "Calculation",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/calculation/",
        "test_type": ["A"],
        "description": "Measures speed and accuracy in basic numerical calculations. Ideal for roles requiring rapid arithmetic such as finance, cashier, or data entry.",
        "job_levels": ["Entry", "Administrative", "Clerical"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": 10,
    },

    # ── PERSONALITY ────────────────────────────────────────────────────────
    {
        "name": "OPQ32r",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq32r/",
        "test_type": ["P"],
        "description": "Occupational Personality Questionnaire. Measures 32 personality characteristics relevant to work performance including relationships, thinking styles and feelings/emotions. Gold-standard for managerial and professional selection.",
        "job_levels": ["Graduate", "Manager", "Director", "Professional", "Executive"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 30,
    },
    {
        "name": "MQ (Motivation Questionnaire)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/motivation-questionnaire-mq/",
        "test_type": ["P"],
        "description": "Measures factors that increase or decrease motivation. Helps predict engagement, retention, and culture-fit for professional and leadership roles.",
        "job_levels": ["Professional", "Manager", "Director", "Executive"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 20,
    },
    {
        "name": "Hogan Personality Inventory (HPI)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/hpi/",
        "test_type": ["P"],
        "description": "Measures normal, bright-side personality characteristics that describe how people relate to others and approach their work when at their best.",
        "job_levels": ["Professional", "Manager", "Director"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 40,
    },
    {
        "name": "Hogan Development Survey (HDS)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/hds/",
        "test_type": ["P"],
        "description": "Measures dark-side personality characteristics — overused strengths that emerge under stress and derail careers. Critical for senior leadership assessment.",
        "job_levels": ["Manager", "Director", "Executive"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 40,
    },
    {
        "name": "Motives, Values, Preferences Inventory (MVPI)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mvpi/",
        "test_type": ["P"],
        "description": "Measures core values, goals, and interests to predict cultural fit and job satisfaction. Often paired with HPI/HDS for comprehensive personality profiling.",
        "job_levels": ["Professional", "Manager", "Director", "Executive"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 30,
    },

    # ── KNOWLEDGE / SKILLS ─────────────────────────────────────────────────
    {
        "name": "Java 8 (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/java-8-new/",
        "test_type": ["K"],
        "description": "Measures knowledge of Java 8 programming language including OOP concepts, lambdas, streams, and collections. Suitable for Java developers at all levels.",
        "job_levels": ["Entry", "Professional", "Manager"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 1,
    },
    {
        "name": "Python (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/python-new/",
        "test_type": ["K"],
        "description": "Measures knowledge of Python programming language including syntax, data structures, and standard libraries. For Python developers and data scientists.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 1,
    },
    {
        "name": "SQL (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sql-new/",
        "test_type": ["K"],
        "description": "Measures knowledge of SQL including queries, joins, aggregations, and database design. Suitable for database developers, analysts, and data engineers.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 1,
    },
    {
        "name": "JavaScript (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/javascript-new/",
        "test_type": ["K"],
        "description": "Measures knowledge of JavaScript including ES6+, DOM manipulation, async patterns, and frameworks. For front-end and full-stack developers.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 1,
    },
    {
        "name": "C# (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/c-sharp-new/",
        "test_type": ["K"],
        "description": "Measures knowledge of C# including .NET framework, LINQ, OOP principles, and async programming. For .NET developers.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 1,
    },
    {
        "name": "C++ (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/c-plus-plus-new/",
        "test_type": ["K"],
        "description": "Measures knowledge of C++ including memory management, STL, templates, and OOP. For systems and embedded software developers.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 1,
    },
    {
        "name": "Automata - Fix (Coding Simulation)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/automata-fix-coding-simulation/",
        "test_type": ["S", "K"],
        "description": "Coding simulation where candidates debug broken code. Tests practical programming ability in a realistic environment across multiple languages.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 5,
    },
    {
        "name": "Automata Pro",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/automata-pro/",
        "test_type": ["S", "K"],
        "description": "Advanced coding simulation measuring real-world programming skills through multi-file projects. Ideal for senior software engineers.",
        "job_levels": ["Professional", "Manager"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": 5,
    },
    {
        "name": "Microsoft Excel (Office 2019)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ms-excel-2019/",
        "test_type": ["K"],
        "description": "Measures proficiency in Microsoft Excel including formulas, pivot tables, charts, and data analysis features.",
        "job_levels": ["Entry", "Administrative", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 5,
    },
    {
        "name": "Microsoft Word (Office 2019)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ms-word-2019/",
        "test_type": ["K"],
        "description": "Measures proficiency in Microsoft Word including formatting, styles, mail merge, and document management.",
        "job_levels": ["Entry", "Administrative", "Clerical"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 5,
    },
    {
        "name": "Financial Accounting (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/financial-accounting-new/",
        "test_type": ["K"],
        "description": "Measures knowledge of financial accounting principles including balance sheets, income statements, and GAAP. For finance and accounting roles.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 2,
    },
    {
        "name": "Accounting and Finance (AFAS)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/accounting-and-finance-afas/",
        "test_type": ["K"],
        "description": "Comprehensive assessment of accounting and finance knowledge for professional accountants and finance managers.",
        "job_levels": ["Professional", "Manager"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 35,
        "languages": 5,
    },

    # ── SITUATIONAL JUDGEMENT / BEHAVIOURAL ────────────────────────────────
    {
        "name": "Sales Solution",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sales-solution/",
        "test_type": ["B"],
        "description": "Situational judgement test for sales roles measuring customer orientation, persuasion, and resilience. Benchmarked against top sales performers.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 10,
    },
    {
        "name": "Customer Contact Scenarios",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/customer-contact-scenarios/",
        "test_type": ["B", "S"],
        "description": "Simulation-based assessment for customer service and contact centre roles. Candidates handle realistic customer interactions across channels.",
        "job_levels": ["Entry", "Operative"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 8,
    },
    {
        "name": "Graduate/Professional Scenarios",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/graduate-professional-scenarios/",
        "test_type": ["B"],
        "description": "Situational judgement test for graduate and early-career professional selection measuring judgement in workplace scenarios.",
        "job_levels": ["Graduate", "Entry-Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 15,
    },
    {
        "name": "Managerial Scenarios",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/managerial-scenarios/",
        "test_type": ["B"],
        "description": "Situational judgement test for managerial selection measuring effectiveness in leading teams, handling conflict, and delivering results.",
        "job_levels": ["Manager", "Senior Manager"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 10,
    },
    {
        "name": "Supervisory Scenarios",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/supervisory-scenarios/",
        "test_type": ["B"],
        "description": "Situational judgement test designed for first-line supervisors and team leaders. Assesses practical supervision and people management skills.",
        "job_levels": ["Supervisor", "Team Lead"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 8,
    },
    {
        "name": "Service Orientation",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/service-orientation/",
        "test_type": ["B", "P"],
        "description": "Measures attitudes and behaviours towards customer service. Relevant for front-line customer service, hospitality, and retail roles.",
        "job_levels": ["Entry", "Operative", "Administrative"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 10,
    },

    # ── SIMULATION ─────────────────────────────────────────────────────────
    {
        "name": "Work Skills Series",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/work-skills-series/",
        "test_type": ["S"],
        "description": "Simulation-based work skills assessments covering typing, data entry, proofreading, and other clerical tasks. For administrative and entry roles.",
        "job_levels": ["Entry", "Administrative", "Clerical"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 5,
    },

    # ── COMPETENCY BASED ───────────────────────────────────────────────────
    {
        "name": "360 Feedback Tool",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/360-feedback/",
        "test_type": ["C"],
        "description": "Multi-rater feedback tool aligned to SHL competency framework. Used for development and performance management across management levels.",
        "job_levels": ["Manager", "Director", "Executive"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 20,
    },

    # ── ADDITIONAL HIGH-FREQUENCY ASSESSMENTS ─────────────────────────────
    {
        "name": "Dependability & Safety Instrument (DSI)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/dependability-and-safety-instrument-dsi/",
        "test_type": ["P", "B"],
        "description": "Measures counterproductive work behaviour tendencies including safety compliance, reliability, and integrity. Critical for safety-sensitive and operational roles.",
        "job_levels": ["Entry", "Operative", "Technician"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 5,
    },
    {
        "name": "Graduate 8.0",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/graduate-8/",
        "test_type": ["A"],
        "description": "Adaptive graduate-level cognitive battery measuring numerical, verbal, and inductive reasoning for high-volume graduate recruitment.",
        "job_levels": ["Graduate"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 36,
        "languages": 20,
    },
    {
        "name": "Professional 8.0",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/professional-8/",
        "test_type": ["A"],
        "description": "Adaptive professional-level cognitive battery for experienced hires and senior professional selection.",
        "job_levels": ["Professional", "Manager"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 36,
        "languages": 20,
    },
    {
        "name": "Operational 7.0",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/operational-7/",
        "test_type": ["A"],
        "description": "Adaptive cognitive battery for operational and trade roles, measuring practical reasoning and problem-solving.",
        "job_levels": ["Operative", "Technician", "Entry"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 28,
        "languages": 15,
    },
    {
        "name": "Workplace English Language Test (WELT-B2/C1)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/workplace-english-language-test/",
        "test_type": ["K"],
        "description": "Measures English language proficiency at B2 and C1 CEFR levels in workplace contexts. Relevant for international hiring and language-critical roles.",
        "job_levels": ["Entry", "Professional", "Graduate"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": 1,
    },
    {
        "name": "SJT - Customer Focus",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sjt-customer-focus/",
        "test_type": ["B"],
        "description": "Situational judgement test measuring customer-centric behaviours and decisions. For customer-facing roles across industries.",
        "job_levels": ["Entry", "Operative", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 8,
    },
    {
        "name": "Hogan Leadership Forecast Series",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/hogan-leadership-forecast-series/",
        "test_type": ["P"],
        "description": "Comprehensive leadership personality assessment combining HPI, HDS, and MVPI for executive and leadership pipeline assessment.",
        "job_levels": ["Director", "Executive"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": 40,
    },
    {
        "name": "Aspects Styles",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/aspects-styles/",
        "test_type": ["P"],
        "description": "Short personality measure of interpersonal and work style for entry-level and volume hiring. Quick to administer with strong predictive validity.",
        "job_levels": ["Entry", "Operative", "Administrative"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": 15,
    },
    {
        "name": "Aspects Potential",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/aspects-potential/",
        "test_type": ["A"],
        "description": "Short cognitive ability assessment for entry-level volume hiring. Measures verbal, numerical, and checking ability quickly.",
        "job_levels": ["Entry", "Operative", "Administrative"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 12,
        "languages": 15,
    },
    {
        "name": "Mechanical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mechanical-reasoning/",
        "test_type": ["A"],
        "description": "Measures understanding of mechanical and physical principles. For engineering, manufacturing, and maintenance roles.",
        "job_levels": ["Entry", "Operative", "Technician"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 10,
    },
    {
        "name": "Spatial Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/spatial-reasoning/",
        "test_type": ["A"],
        "description": "Measures ability to think in three dimensions and mentally rotate shapes. For design, engineering, and technical roles.",
        "job_levels": ["Entry", "Professional", "Technician"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": 10,
    },
    {
        "name": "Cybersecurity Assessment",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/cybersecurity-assessment/",
        "test_type": ["K"],
        "description": "Measures knowledge of cybersecurity principles including network security, threat analysis, and compliance frameworks. For security roles.",
        "job_levels": ["Entry", "Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 35,
        "languages": 2,
    },
    {
        "name": "Data Engineering",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/data-engineering/",
        "test_type": ["K"],
        "description": "Measures skills in data pipeline development, ETL, and big data technologies including Spark, Hadoop, and cloud platforms.",
        "job_levels": ["Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 35,
        "languages": 1,
    },
    {
        "name": "Machine Learning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/machine-learning/",
        "test_type": ["K"],
        "description": "Measures knowledge of ML algorithms, model evaluation, feature engineering, and deployment practices. For data science and ML engineering roles.",
        "job_levels": ["Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 35,
        "languages": 1,
    },
    {
        "name": "Project Management (PMP Focus)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/project-management/",
        "test_type": ["K"],
        "description": "Measures knowledge of project management methodologies including Agile, Scrum, and PMP frameworks. For project and program managers.",
        "job_levels": ["Professional", "Manager"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": 3,
    },
    {
        "name": "Technology Professional 8.0",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/technology-professional-8/",
        "test_type": ["A"],
        "description": "Adaptive cognitive battery specifically normed on technology professionals. Measures analytical reasoning relevant to tech roles.",
        "job_levels": ["Professional", "Manager"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 36,
        "languages": 10,
    },
    {
        "name": "Sales Potential Questionnaire",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sales-potential-questionnaire/",
        "test_type": ["P"],
        "description": "Measures sales-relevant personality traits including drive, resilience, influence, and customer focus. For all levels of sales hiring.",
        "job_levels": ["Entry", "Professional", "Manager"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": 15,
    },
    {
        "name": "Contact Centre Solution",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/contact-centre-solution/",
        "test_type": ["B", "K"],
        "description": "End-to-end assessment for contact centre hiring covering typing, comprehension, customer handling scenarios, and work style.",
        "job_levels": ["Entry", "Operative"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": 8,
    },
]

# Build an index for quick lookup
CATALOG_INDEX = {item["name"].lower(): item for item in CATALOG}

TEST_TYPE_LABELS = {
    "A": "Ability/Aptitude",
    "B": "Behaviour/Situational Judgement",
    "C": "Competency",
    "K": "Knowledge/Skills",
    "P": "Personality/Motivation",
    "S": "Simulation",
}
